### ISSUE TITLE
现在项目编译出现了有一个错误

### ISSUE THREAD

**Issue by cywcyw123** [cdalwyn/BaseMvvmScaffold#1]
![C0C05368-E902-461a-AE1D-B9B1549FCA1C](https://user-images.githubusercontent.com/66299562/126426834-e78686bf-3324-4fbc-a176-1599ea74d9ee.png)

**Comment by cdalwyn** [comment]
> ![C0C05368-E902-461a-AE1D-B9B1549FCA1C](https://user-images.githubusercontent.com/66299562/126426834-e78686bf-3324-4fbc-a176-1599ea74d9ee.png)

拉取最新代码更新了Gradle依赖适配AS北极狐版本并重新编译
